/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author GOLU
 */
public class Acc_picture extends javax.swing.JFrame {
int refid;
String picpath="";
String signpath="";
    /**
     * Creates new form Acc_picture
     */
    public Acc_picture(int id) {
        initComponents();
        refid=id;
        System.out.println(refid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblpic = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblsign = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(null);
        getContentPane().add(lblpic);
        lblpic.setBounds(71, 95, 131, 126);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 102, 255));
        jButton1.setText("Add Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(71, 46, 131, 31);

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(213, 297, 124, 33);
        getContentPane().add(lblsign);
        lblsign.setBounds(319, 95, 131, 126);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 102, 255));
        jButton3.setText("Add Signature");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(308, 46, 159, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\GOLU\\Desktop\\edit_pic\\photo_pic.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{  
        
        java.io.File fi=null;
        javax.swing.JFileChooser flch= new javax.swing.JFileChooser(); 
        int res =flch.showOpenDialog(null);
        if(res==javax.swing.JFileChooser.APPROVE_OPTION)
         fi=flch.getSelectedFile();
        picpath=fi.getPath();
        javax.swing.ImageIcon imcn=new javax.swing.ImageIcon(fi.getPath());
        lblpic.setIcon(imcn);
        
        
        
        }catch(Exception e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{  
       
        java.io.File fl=null;
        javax.swing.JFileChooser flchoser= new javax.swing.JFileChooser(); 
        int res =flchoser.showOpenDialog(null);
        if(res==javax.swing.JFileChooser.APPROVE_OPTION)
         fl=flchoser.getSelectedFile();
        signpath=fl.getPath();
        javax.swing.ImageIcon imcn1=new javax.swing.ImageIcon(fl.getPath());
        lblsign.setIcon(imcn1);
        
        
        
        }catch(Exception e){}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            upload();
        }catch(Exception e){
        
        
        System.out.println(e.getMessage());}
    }//GEN-LAST:event_jButton2ActionPerformed

    public void upload()throws Exception{
    
        try{
          
       Class.forName("oracle.jdbc.driver.OracleDriver");                  
       Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","GOLU","852");
       PreparedStatement ps5 = con.prepareStatement("update  accounts set pic=?,sign=? where refid= ?");
       ps5.setString(1,picpath);
       ps5.setString(2,signpath);
       ps5.setInt(3,refid);
       System.out.println("DP  is" + picpath);
       System.out.println("Signature pic is" + signpath);
       System.out.println("refid is" + refid);
       ps5.executeQuery();
       con.close();
       
       JOptionPane.showMessageDialog(null, "Record Update SuccessFully");
        }catch(Exception e){}
        
    }
  
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblpic;
    private javax.swing.JLabel lblsign;
    // End of variables declaration//GEN-END:variables
}
