package banking;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.net.*;
import javax.swing.border.Border;


public class AddNewBranch extends javax.swing.JFrame{

    JLabel sub;
    Border borderRed,borderBlack;
    /**
     * Creates new form AddNewBranch
     */
    public AddNewBranch() {
       sub = new JLabel(" ");
       borderRed = BorderFactory.createLineBorder(Color.red);
		borderBlack = BorderFactory.createLineBorder(Color.gray);
        initComponents();
        setBounds(150,100,970,580);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
//Initialize all Visibele COmponent
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        branchCode = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        branchName = new javax.swing.JTextField();
        ifsc = new javax.swing.JTextField();
        branchMng = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        landMark = new javax.swing.JTextField();
        l8 = new javax.swing.JLabel();
        district = new javax.swing.JTextField();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        l12 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        branchConNo = new javax.swing.JTextField();
        sbmt = new javax.swing.JButton();
        clr = new javax.swing.JButton();
        sbmt1 = new javax.swing.JButton();
        state = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Add New Branch"); //set title of form
        getContentPane().setLayout(null);

        l1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(102, 102, 255));
        l1.setText("Branch Details");
        getContentPane().add(l1);
        l1.setBounds(10, 10, 184, 30);

        l2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(102, 0, 0));
        l2.setText("Branch Code *");
        getContentPane().add(l2);
        l2.setBounds(90, 50, 102, 20);

        branchCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        branchCode.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                branchCodeInputMethodTextChanged(evt);
            }
        });
        getContentPane().add(branchCode);
        branchCode.setBounds(270, 40, 170, 30);

        l3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l3.setForeground(new java.awt.Color(102, 0, 0));
        l3.setText("Branch Name *");
        getContentPane().add(l3);
        l3.setBounds(90, 90, 106, 17);

        branchName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(branchName);
        branchName.setBounds(270, 80, 170, 30);

        ifsc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(ifsc);
        ifsc.setBounds(270, 120, 170, 30);

        branchMng.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(branchMng);
        branchMng.setBounds(270, 160, 192, 30);

        l4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l4.setForeground(new java.awt.Color(102, 0, 0));
        l4.setText("IFSC Code *");
        getContentPane().add(l4);
        l4.setBounds(100, 120, 93, 28);

        l5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l5.setForeground(new java.awt.Color(102, 0, 0));
        l5.setText("Branch Manager *");
        getContentPane().add(l5);
        l5.setBounds(80, 160, 126, 28);

        l6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l6.setForeground(new java.awt.Color(102, 102, 255));
        l6.setText("Branch Address");
        getContentPane().add(l6);
        l6.setBounds(20, 210, 184, 29);

        l7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l7.setForeground(new java.awt.Color(102, 0, 0));
        l7.setText("Landmark/Street *");
        getContentPane().add(l7);
        l7.setBounds(80, 250, 143, 20);

        landMark.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(landMark);
        landMark.setBounds(280, 250, 192, 30);

        l8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l8.setForeground(new java.awt.Color(102, 0, 0));
        l8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l8.setText("District *");
        getContentPane().add(l8);
        l8.setBounds(520, 250, 78, 20);

        district.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(district);
        district.setBounds(680, 250, 160, 30);

        l9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l9.setForeground(new java.awt.Color(102, 0, 0));
        l9.setText("State/UT *");
        getContentPane().add(l9);
        l9.setBounds(110, 300, 90, 17);

        l10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l10.setForeground(new java.awt.Color(102, 0, 0));
        l10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l10.setText("PIN *");
        getContentPane().add(l10);
        l10.setBounds(540, 300, 49, 17);

        pin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(pin);
        pin.setBounds(680, 290, 160, 30);

        l12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l12.setForeground(new java.awt.Color(102, 0, 0));
        l12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l12.setText("Branch Contact No.  *");
        getContentPane().add(l12);
        l12.setBounds(500, 340, 164, 17);

        l11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l11.setForeground(new java.awt.Color(102, 0, 0));
        l11.setText("City *");
        getContentPane().add(l11);
        l11.setBounds(120, 340, 61, 17);

        city.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(city);
        city.setBounds(280, 340, 180, 30);

        branchConNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(branchConNo);
        branchConNo.setBounds(680, 330, 160, 30);

        sbmt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sbmt.setForeground(new java.awt.Color(0, 51, 51));
        sbmt.setText("Submit");
        sbmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmtActionPerformed(evt);
            }
        });
        getContentPane().add(sbmt);
        sbmt.setBounds(200, 420, 157, 40);

        clr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clr.setForeground(new java.awt.Color(0, 51, 51));
        clr.setText("Clear");
        clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrActionPerformed(evt);
            }
        });
        getContentPane().add(clr);
        clr.setBounds(400, 420, 149, 40);

        sbmt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sbmt1.setForeground(new java.awt.Color(0, 51, 51));
        sbmt1.setText("Cancel");
        sbmt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmt1ActionPerformed(evt);
            }
        });
        getContentPane().add(sbmt1);
        sbmt1.setBounds(580, 420, 157, 40);

        state.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        state.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<SELECT>", "Andaman and Nicobar Islands", "Andra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chandigarh", "Chhattisgarh", "Dadar and Nagar Haveli", "Daman and Diu", "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka", "Kerala", "Lakshadeep", "Madya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Orissa", "Pondicherry", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Tripura", "Uttaranchal", "Uttar Pradesh", "West Bengal" }));
        state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateActionPerformed(evt);
            }
        });
        getContentPane().add(state);
        state.setBounds(280, 300, 200, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("Pic destination File")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 950, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sbmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmtActionPerformed
             try{ submit();} catch(Exception e){
       
       }        // TODO add your handling code here:
    }//GEN-LAST:event_sbmtActionPerformed

    private void clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrActionPerformed
        try{ clear();
        }catch(Exception e){
       
       }
    }//GEN-LAST:event_clrActionPerformed

    private void sbmt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmt1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_sbmt1ActionPerformed

    private void branchCodeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_branchCodeInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_branchCodeInputMethodTextChanged

    private void stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateActionPerformed
    
    public void submit() throws Exception
    {
        if(branchCode.getText().equals(""))//check if branch code is Empty
			{
				branchCode.setBorder(borderRed); //make that box red 
                                //show in pop-up window that branch code box is Empty
				JOptionPane.showMessageDialog((Component)null,"Branch Code Empty","Warning",JOptionPane.WARNING_MESSAGE);
				
			}
    else if(this.branchName.getText().equals("")) //check if branch Name is Empty
			{
                           branchName.setBorder(borderRed);//make that box red 
                                //show in pop-up window that branch name box is Empty
				JOptionPane.showMessageDialog((Component)null,"Branch Name Empty","Warning",JOptionPane.WARNING_MESSAGE);
                        }
    else if(this.ifsc.getText().equals(""))//check if branch Ifsc is Empty
			{
                           ifsc.setBorder(borderRed);//make that box red 
                                //show in pop-up window that Ifsc box is Empty
                           
				JOptionPane.showMessageDialog((Component)null,"IFSC Code Empty","Warning",JOptionPane.WARNING_MESSAGE);
                        }
    else if(this.branchMng.getText().equals("")) //check if branch manager name Box is Empty
			{
                           branchMng.setBorder(borderRed);//make that box red 
                                //show in pop-up window that branch manager box is Empty
				JOptionPane.showMessageDialog((Component)null,"Enter Branch Manager Name","Warning",JOptionPane.WARNING_MESSAGE);
                        }
    else if(this.landMark.getText().equals("")) //check if landmark Box is Empty
			{
                           landMark.setBorder(borderRed);//make that box red 
                                //show in pop-up window that landmark box is Empty
				JOptionPane.showMessageDialog((Component)null,"Enter land Mark","Warning",JOptionPane.WARNING_MESSAGE);
                        }
    else if(this.district.getText().equals(""))
			{
                           district.setBorder(borderRed);
				JOptionPane.showMessageDialog((Component)null,"District Name is Empty","Warning",JOptionPane.WARNING_MESSAGE);
                        }
    else if(this.state.getSelectedItem().equals("<SELECT>")){ //check if state combo box is selecte As SELECT
                                        state.setBorder(borderRed); //make that box red 
                                //show in pop-up window that state checkBox box is Empty
					JOptionPane.showMessageDialog((Component)null,"Choose State","Warning",JOptionPane.WARNING_MESSAGE);
					
			}
    else if(this.pin.getText().equals(""))
			{
                           pin.setBorder(borderRed);
				JOptionPane.showMessageDialog((Component)null,"Pin Code Empty","Warning",JOptionPane.WARNING_MESSAGE);
                        }
    else if(this.city.getText().equals(""))
			{
                           city.setBorder(borderRed);
				JOptionPane.showMessageDialog((Component)null,"City Empty","Warning",JOptionPane.WARNING_MESSAGE);
                        }
    else if(this.branchConNo.getText().equals(""))
			{
                           branchConNo.setBorder(borderRed);
				JOptionPane.showMessageDialog((Component)null,"Branch Contact No. Empty","Warning",JOptionPane.WARNING_MESSAGE);
                        }
    
			else{
				branchCode.setBorder(borderBlack);
                                state.setBorder(borderRed);
    try{
					 Class.forName("oracle.jdbc.driver.OracleDriver"); //resister with OracleDriver
			         Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","USERNAME","PASSWORD"); //make connectionby giving userName and Password
					PreparedStatement ps = con.prepareStatement("insert into Branch values(bankid.NEXTVAL,?,?,?,?,?,?,?,?,?,?)");//Insert data into branch table by taking input from corresponding textBox 
					//ps.setInt(1,Integer.parseInt(t1.getText()));
					ps.setString(1,this.branchCode.getText().toUpperCase());
					ps.setString(2,branchName.getText());
					ps.setString(3,ifsc.getText().toUpperCase());
					ps.setString(4,branchMng.getText());
					ps.setString(5,landMark.getText());
					ps.setString(6,district.getText());
					ps.setString(7,state.getSelectedItem().toString());
					ps.setString(8,pin.getText());
					ps.setString(9,city.getText());
					ps.setString(10,branchConNo.getText());
					 
					ps.executeQuery();  //execute Query
					con.close();//connection close
					
					JOptionPane.showMessageDialog(sub, "Record Save SuccessFully");
				}
				catch(Exception ex){
					//System.out.println(ex.getMessage());
					System.err.println("Got an exception! "); 
					System.err.println(ex.getMessage());
				}
				
			}
    
    
    }
    
     public void clear() throws Exception  //when user click clear button all textBox will be Empty
     {
   
			branchCode.setText(""); branchName.setText(""); ifsc.setText(""); branchMng.setText(""); landMark.setText("");
			district.setText("");
                        //state.setText("");
                        pin.setText(""); city.setText(""); branchConNo.setText("");
     }
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField branchCode;
    private javax.swing.JTextField branchConNo;
    private javax.swing.JTextField branchMng;
    private javax.swing.JTextField branchName;
    private javax.swing.JTextField city;
    private javax.swing.JButton clr;
    private javax.swing.JTextField district;
    private javax.swing.JTextField ifsc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JTextField landMark;
    private javax.swing.JTextField pin;
    private javax.swing.JButton sbmt;
    private javax.swing.JButton sbmt1;
    private javax.swing.JComboBox state;
    // End of variables declaration//GEN-END:variables
}
