package banking;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.net.*;
import javax.swing.border.Border;
import com.toedter.calendar.JDateChooser;

public class AddNewAccount extends javax.swing.JFrame{

    JLabel message;
    ScrollPane scpn;
    /**
     * 
     * Creates new form AddNewAccount
     */
    public AddNewAccount() {
        
        message = new JLabel(" ");
        scpn=new ScrollPane();
        //scpn.add(this.Form);
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        landMark = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        prefix = new javax.swing.JComboBox();
        l6 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();
        l26 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        district = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        l7 = new javax.swing.JLabel();
        nomName = new javax.swing.JTextField();
        l19 = new javax.swing.JLabel();
        telNo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        mri = new javax.swing.JComboBox();
        mobNo = new javax.swing.JTextField();
        l21 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        lName = new javax.swing.JTextField();
        l16 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        l24 = new javax.swing.JLabel();
        fNAME = new javax.swing.JTextField();
        nomRelation = new javax.swing.JTextField();
        mName = new javax.swing.JTextField();
        l27 = new javax.swing.JLabel();
        gName = new javax.swing.JTextField();
        l10 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        accType = new javax.swing.JComboBox();
        jDateChooser1 = new org.netbeans.modules.form.InvalidComponent();
        pre1 = new javax.swing.JComboBox();
        p2 = new javax.swing.JPanel();
        male = new javax.swing.JRadioButton();
        fem = new javax.swing.JRadioButton();
        l22 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        l25 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        jDateChooser2 = new org.netbeans.modules.form.InvalidComponent();
        l8 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        nation = new javax.swing.JComboBox();
        l1 = new javax.swing.JLabel();
        bCode = new javax.swing.JTextField();
        mMaidenName = new javax.swing.JTextField();
        father = new javax.swing.JComboBox();
        l14 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        l13 = new javax.swing.JLabel();
        accNo = new javax.swing.JTextField();
        ifsc = new javax.swing.JTextField();
        l11 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setTitle("New Account Form");
        setFocusTraversalPolicyProvider(true);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1247, 2297));

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 987));

        landMark.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        l4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l4.setForeground(new java.awt.Color(102, 0, 0));
        l4.setText("Name of  *");

        prefix.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prefix.setForeground(new java.awt.Color(153, 153, 255));
        prefix.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr.", "Mrs" }));

        l6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l6.setForeground(new java.awt.Color(102, 0, 51));
        l6.setText("Gender");

        l23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l23.setForeground(new java.awt.Color(102, 0, 0));
        l23.setText("Nominee Date Of Birth");

        l26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l26.setForeground(new java.awt.Color(102, 0, 0));
        l26.setText("Branch Code *");

        l18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l18.setForeground(new java.awt.Color(102, 0, 0));
        l18.setText("Mobile No. *");

        l12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l12.setForeground(new java.awt.Color(102, 0, 0));
        l12.setText("Landmark/Street *");

        district.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        l3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l3.setForeground(new java.awt.Color(102, 0, 0));
        l3.setText("NAME *");

        email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        l7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l7.setForeground(new java.awt.Color(102, 0, 0));
        l7.setText("Nationality");

        nomName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        l19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l19.setForeground(new java.awt.Color(102, 0, 0));
        l19.setText("Email Address");

        telNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mri.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mri.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Single", "Married" }));

        mobNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        l21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l21.setForeground(new java.awt.Color(102, 0, 0));
        l21.setText("Nominee Name");

        city.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lName.setForeground(new java.awt.Color(51, 51, 51));

        l16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l16.setForeground(new java.awt.Color(102, 0, 0));
        l16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l16.setText("City *");

        uid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uidActionPerformed(evt);
            }
        });

        l24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l24.setForeground(new java.awt.Color(102, 0, 0));
        l24.setText("Age");

        fNAME.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fNAME.setForeground(new java.awt.Color(51, 51, 51));

        nomRelation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        mName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mName.setForeground(new java.awt.Color(51, 51, 51));

        l27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l27.setForeground(new java.awt.Color(102, 0, 0));
        l27.setText("IFSC *");

        gName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gName.setForeground(new java.awt.Color(51, 51, 51));

        l10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l10.setForeground(new java.awt.Color(102, 0, 0));
        l10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l10.setText("UID");

        l5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l5.setForeground(new java.awt.Color(102, 0, 0));
        l5.setText("Date of Birth *");

        l2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(102, 0, 0));
        l2.setText("Account Type *");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        accType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        accType.setForeground(new java.awt.Color(153, 153, 255));
        accType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select>", "Saving Account", "Current Account" }));

        pre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pre1.setForeground(new java.awt.Color(153, 153, 255));
        pre1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr.", "Mrs" }));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        male.setText("MALE");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        buttonGroup1.add(fem);
        fem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fem.setText("FEMALE");

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addComponent(male)
                .addGap(18, 18, 18)
                .addComponent(fem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male)
                    .addComponent(fem)))
        );

        l22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l22.setForeground(new java.awt.Color(102, 0, 0));
        l22.setText("Nominee Relation");

        pin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        l25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l25.setForeground(new java.awt.Color(102, 0, 0));
        l25.setText("Account No *");

        l9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l9.setForeground(new java.awt.Color(102, 0, 0));
        l9.setText("Applicant's Marital Status *");

        l8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l8.setForeground(new java.awt.Color(102, 0, 0));
        l8.setText("Mother 's Madien Name");

        l20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l20.setForeground(new java.awt.Color(51, 51, 255));
        l20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l20.setText("Nominee Details");

        l15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l15.setForeground(new java.awt.Color(102, 0, 0));
        l15.setText("PIN *");

        nation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "INDIAN", "OTHER" }));

        l1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(102, 102, 255));
        l1.setText("Personal Details");

        bCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bCode.setForeground(new java.awt.Color(51, 51, 51));

        mMaidenName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        father.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        father.setForeground(new java.awt.Color(204, 0, 0));
        father.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select---", "Father/Guardian", "Husband" }));

        l14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l14.setForeground(new java.awt.Color(102, 0, 0));
        l14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l14.setText("State/UT *");

        state.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        l13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l13.setForeground(new java.awt.Color(102, 0, 0));
        l13.setText("District *");

        accNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        accNo.setForeground(new java.awt.Color(51, 51, 51));

        ifsc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ifsc.setForeground(new java.awt.Color(51, 51, 51));

        l11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l11.setForeground(new java.awt.Color(51, 51, 255));
        l11.setText("Pemanent Address");

        l17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l17.setForeground(new java.awt.Color(102, 0, 0));
        l17.setText("Telephone No. (With STD Code)");

        age.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        age.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("@");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select Domain--", "gmail.com", "yahoo.com", "hotmail.com", "rediff.com" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(l14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mobNo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telNo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nomRelation, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(l23, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(landMark, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(l9)
                                        .addGap(44, 44, 44)
                                        .addComponent(mri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(gName, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l11, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l20, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l17, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l19, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l18, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(l21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(l22, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jButton1)
                        .addGap(76, 76, 76)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l2)
                                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(l4)
                                    .addGap(41, 41, 41)))
                            .addComponent(l5)
                            .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(l8)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(father, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pre1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(l24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nation, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(mMaidenName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(92, 92, 92)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(district, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(l27, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(ifsc, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(68, 68, 68)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(l15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(l25, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(accNo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(accType, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(l26, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bCode, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l2)
                    .addComponent(accType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l26, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ifsc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fNAME)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lName)
                        .addComponent(prefix, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l4)
                    .addComponent(father, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gName))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nation, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l8)
                    .addComponent(mMaidenName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mri, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(l11)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(landMark, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(district, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l14))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telNo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jComboBox1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(l20)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomRelation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1174, Short.MAX_VALUE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
                .addGap(278, 278, 278))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{ clear();
        }catch(Exception e){

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{ submit();} catch(Exception e){

        }
    }//GEN-LAST:event_jButton1ActionPerformed
String genderOpt;
    public void submit() throws Exception
      {
          int refid=0; //initialization of refid
      //check all visible componet is filled with appropriate data by user
      //  if there is any empty then it will show in pop-up that respective componet is not appropriate filled    
         if(this.bCode.getText().equals(""))
			{
				
				JOptionPane.showMessageDialog((Component)null,"Invalid Branch Code Please Enter a Valid Branch CODE","Warning",JOptionPane.WARNING_MESSAGE);
                       }
       
         else if(this.ifsc.getText().equals(""))
			{
				JOptionPane.showMessageDialog((Component)null,"Invalid IFSC Code Please Enter a Valid IFSC CODE ","Warning",JOptionPane.WARNING_MESSAGE);
				
			}
			else if(this.accType.getSelectedItem().equals("<Select>")){
					JOptionPane.showMessageDialog((Component)null,"Please Select Account Type","Warning",JOptionPane.WARNING_MESSAGE);
					
			}
                        else if(fNAME.getText().equals(""))
			{ 
				
				JOptionPane.showMessageDialog((Component)null,"Enter First Name","Warning",JOptionPane.WARNING_MESSAGE);
			
			}
                         else if(this.lName.getText().equals(""))
			{ 
				
				JOptionPane.showMessageDialog((Component)null,"Enter Last Name","Warning",JOptionPane.WARNING_MESSAGE);
			
			}
                          else if(gName.getText().equals(""))
			{ 
				
				JOptionPane.showMessageDialog((Component)null,"Enter Guardian Name","Warning",JOptionPane.WARNING_MESSAGE);
			
			}
                           else if(mMaidenName.getText().equals(""))
			{ 
				
				JOptionPane.showMessageDialog((Component)null,"Enter mother's Name","Warning",JOptionPane.WARNING_MESSAGE);
			
			}
                            else if(landMark.getText().equals(""))
			{ 
				
				JOptionPane.showMessageDialog((Component)null,"Enter Landmark","Warning",JOptionPane.WARNING_MESSAGE);
			
			}
                             else if(district.getText().equals(""))
			{ 
				
				JOptionPane.showMessageDialog((Component)null,"Enter District","Warning",JOptionPane.WARNING_MESSAGE);
			
			}
                             else if(state.getText().equals(""))
			{ 
				
				JOptionPane.showMessageDialog((Component)null,"Enter State","Warning",JOptionPane.WARNING_MESSAGE);
			
			}
                             else if(city.getText().equals(""))
			{ 
				
				JOptionPane.showMessageDialog((Component)null,"Enter City","Warning",JOptionPane.WARNING_MESSAGE);
			
			}
                             else if(mobNo.getText().equals(""))
			{ 
				
				JOptionPane.showMessageDialog((Component)null,"Enter mobile No.","Warning",JOptionPane.WARNING_MESSAGE);
			
			}
                             else if(pin.getText().equals(""))
			{ 
				
				JOptionPane.showMessageDialog((Component)null,"Enter Pin","Warning",JOptionPane.WARNING_MESSAGE);
			
			}
                             else if(email.getText().equals(""))
			{ 
				
				JOptionPane.showMessageDialog((Component)null,"Enter E-mail","Warning",JOptionPane.WARNING_MESSAGE);
			
			}
                             else if(nomName.getText().equals(""))
			{ 
				
				JOptionPane.showMessageDialog((Component)null,"Enter Nominise Name","Warning",JOptionPane.WARNING_MESSAGE);
			
			}
                             else if(nomRelation.getText().equals(""))
			{ 
				
				JOptionPane.showMessageDialog((Component)null,"Enter Nominise Relation","Warning",JOptionPane.WARNING_MESSAGE);
			
			}
                           
                             
                             
			else if(this.father.getSelectedItem().equals("---Select---")){
					JOptionPane.showMessageDialog((Component)null,"Please Select Guardian Type","Warning",JOptionPane.WARNING_MESSAGE);
					
			}
			else if(this.nation.getSelectedItem().equals("--Select--")){
					JOptionPane.showMessageDialog((Component)null,"Please Select Nationality","Warning",JOptionPane.WARNING_MESSAGE);
					
			}
			else if(this.mri.getSelectedItem().equals("--Select--")){
					JOptionPane.showMessageDialog((Component)null,"Please Select Marital Status","Warning",JOptionPane.WARNING_MESSAGE);
					
			}
                       
                        else if(this.jComboBox1.getSelectedItem().equals("--Select Domain--")){
					JOptionPane.showMessageDialog((Component)null,"Please Select Valid domain","Warning",JOptionPane.WARNING_MESSAGE);
			 System.out.println("jhbfg");		
			}
			    
			else{
                            java.text.SimpleDateFormat ft = new java.text.SimpleDateFormat("dd/MM/yyyy");
				String dobstr=ft.format(this.jDateChooser1.getDate());
                                String nomdob = ft.format(this.jDateChooser2.getDate());
				try{
                                    
                                    refid = getrfId();
                                    //resister with oracle driver
					 Class.forName("oracle.jdbc.driver.OracleDriver");
                                         //make connection by signing with user nameand password
			         Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","GOLU","852");
				//store all data in sql in string from 	
                                   String sql= "insert into accounts(REFID,ACCTYPE,BCODE,IFSCODE,ACCNO,PREFIX,FIRSTNAME,MIDNAME,LASTNAME,";
                                    sql+="GUARDIAN,PREFIX1,GUARDIANNAME,DOB,AGE,NATION,GENDER,MOTHER,MARITAL,UIDNO,STREET,DIST,STATE,CITY, ";
                                            sql+= "PIN,PHONE,MOBILE,EMAIL,NOMINNAME,NOMINREL,NOMINDOB) ";
                                     sql+="values ("+refid+",?,?,?,?,?,?,?,?,?,?,?,to_date(?,'dd/mm/yyyy'),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,to_date(?,'dd/mm/yyyy'))";
                                 
                                 
                                 
                                 PreparedStatement ps1 = con.prepareStatement(sql);
					
					if(male.isSelected() == true){
							genderOpt = "Male";
					}
					else if(fem.isSelected() == true){
							genderOpt = "Female";
					}
               // Insert all data in database according to attribute
					ps1.setString(1,this.accType.getSelectedItem().toString());
					ps1.setString(2,bCode.getText().toUpperCase());
					ps1.setString(3,ifsc.getText().toUpperCase());
					ps1.setInt(4,Integer.parseInt(accNo.getText().trim()));
					ps1.setString(5,this.prefix.getSelectedItem().toString());
					ps1.setString(6,fNAME.getText());
					ps1.setString(7,mName.getText());
					ps1.setString(8,lName.getText());
					ps1.setString(9,this.father.getSelectedItem().toString());
					ps1.setString(10,this.pre1.getSelectedItem().toString());
					ps1.setString(11,gName.getText());
                                        
					ps1.setString(12,dobstr);
					ps1.setInt(13,Integer.parseInt(age.getText().trim()));
					ps1.setString(14,this.nation.getSelectedItem().toString());
					ps1.setString(15,genderOpt);
					ps1.setString(16,mMaidenName.getText());
					ps1.setString(17,this.mri.getSelectedItem().toString());
					ps1.setInt(18,Integer.parseInt(uid.getText().trim()));
					ps1.setString(19,landMark.getText());
					ps1.setString(20,district.getText());
					ps1.setString(21,state.getText());
					ps1.setString(22,city.getText());
					ps1.setInt(23,Integer.parseInt(pin.getText().trim()));
					ps1.setString(24,telNo.getText());
					ps1.setString(25,mobNo.getText());
					ps1.setString(26,email.getText()+this.jLabel1.getText()+this.jComboBox1.getSelectedItem());
					ps1.setString(27,nomName.getText());
					ps1.setString(28,nomRelation.getText());
					ps1.setString(29,nomdob);
					
					ps1.executeQuery();
					con.close();
					JOptionPane.showMessageDialog(message, "Record Save Successfully Now Going to Final Step");
					Acc_picture acpic=new Acc_picture(refid);
                                        acpic.setVisible(true);
                                        acpic.setBounds(280,150,550,420);

                                           this.setVisible(false);
				}
				catch(Exception ex){
					
				
					JOptionPane.showMessageDialog(message,ex.getMessage());
				}
				
				}
          
          
      }
    public void clear() throws Exception{  //when user press clear button 
        
    fNAME.setText(""); mName.setText(""); lName.setText(""); gName.setText("");  mMaidenName.setText("");jDateChooser1.setDate(null);
     uid.setText(""); landMark.setText(""); district.setText(""); state.setText(""); pin.setText(""); city.setText(""); age.setText("");
     telNo.setText(""); mobNo.setText(""); email.setText(""); nomName.setText(""); nomRelation.setText(""); this.jDateChooser2.setDate(null);
    
    
    }
      
   public int getrfId()  // getting size from database
{
	int Size=0;
	try{
	    Class.forName("oracle.jdbc.driver.OracleDriver");
		Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","GOLU","852");
        PreparedStatement ps=con.prepareStatement("Select max(refid)+1 from accounts");
		 ResultSet rs = ps.executeQuery();
			 while(rs.next())
          {
			   Size=rs.getInt(1);
		  }}catch(Exception ex){System.out.println(ex.getMessage());}
		  return Size;
	
} 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNo;
    private javax.swing.JComboBox accType;
    private javax.swing.JTextField age;
    private javax.swing.JTextField bCode;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField city;
    private javax.swing.JTextField district;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fNAME;
    private javax.swing.JComboBox father;
    private javax.swing.JRadioButton fem;
    private javax.swing.JTextField gName;
    private javax.swing.JTextField ifsc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private org.netbeans.modules.form.InvalidComponent jDateChooser1;
    private org.netbeans.modules.form.InvalidComponent jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l19;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l20;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l22;
    private javax.swing.JLabel l23;
    private javax.swing.JLabel l24;
    private javax.swing.JLabel l25;
    private javax.swing.JLabel l26;
    private javax.swing.JLabel l27;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JTextField lName;
    private javax.swing.JTextField landMark;
    private javax.swing.JTextField mMaidenName;
    private javax.swing.JTextField mName;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mobNo;
    private javax.swing.JComboBox mri;
    private javax.swing.JComboBox nation;
    private javax.swing.JTextField nomName;
    private javax.swing.JTextField nomRelation;
    private javax.swing.JPanel p2;
    private javax.swing.JTextField pin;
    private javax.swing.JComboBox pre1;
    private javax.swing.JComboBox prefix;
    private javax.swing.JTextField state;
    private javax.swing.JTextField telNo;
    private javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables
}
