package banking;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.net.*;
import javax.swing.border.Border;

/**
 *
 * @author GOLU
 */
public class CheckBalence extends javax.swing.JFrame {
     Border borderRed,borderBlack;
     int cnt=0;
    /**
     * Creates new form CheckBalence
     */
    public CheckBalence() {
        borderBlack=BorderFactory.createLineBorder(Color.gray);
	    borderRed=BorderFactory.createLineBorder(Color.red);
        initComponents();
        
        //first make all phisical component invisible
        l2.setVisible(false);l3.setVisible(false);l4.setVisible(false);l5.setVisible(false);sub1.setVisible(false);
        setBounds(180,100,817,450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        sub = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        piclabel = new javax.swing.JLabel();
        sub1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Balance Form");
        getContentPane().setLayout(null);

        l1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(102, 0, 0));
        l1.setText("Enter Account No.");
        getContentPane().add(l1);
        l1.setBounds(54, 89, 164, 33);

        t1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(265, 90, 174, 33);

        sub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sub.setForeground(new java.awt.Color(0, 51, 51));
        sub.setText("Check Balance");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        getContentPane().add(sub);
        sub.setBounds(480, 90, 165, 35);

        l2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(102, 0, 0));
        l2.setText("Name");
        getContentPane().add(l2);
        l2.setBounds(115, 160, 61, 34);

        l3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(l3);
        l3.setBounds(265, 160, 149, 34);

        l4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l4.setForeground(new java.awt.Color(102, 0, 0));
        l4.setText("Total Balance");
        getContentPane().add(l4);
        l4.setBounds(54, 213, 122, 22);

        l5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(l5);
        l5.setBounds(265, 213, 149, 34);
        getContentPane().add(piclabel);
        piclabel.setBounds(530, 160, 130, 120);

        sub1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sub1.setForeground(new java.awt.Color(0, 51, 51));
        sub1.setText("cancel");
        sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub1ActionPerformed(evt);
            }
        });
        getContentPane().add(sub1);
        sub1.setBounds(260, 310, 91, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\GOLU\\Desktop\\New folder\\images\\balence01.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
       try{
       takeData(); //call takeDate() to take all data from databse
       }catch(Exception e){}
    }//GEN-LAST:event_subActionPerformed

    private void sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub1ActionPerformed
       setVisible(false);
    }//GEN-LAST:event_sub1ActionPerformed
public void takeData() throws Exception{
if(t1.getText().equals(""))
			{ 
				t1.setBorder(borderRed);
				JOptionPane.showMessageDialog((Component)null,"Please Enter Account Number","Warning",JOptionPane.WARNING_MESSAGE);
			}
		else
		    {
				t1.setBorder(borderBlack);
		try{
			Class.forName("oracle.jdbc.driver.OracleDriver");
			Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","GOLU","852");
			//we select name image and balance of that person
                        PreparedStatement ps=con.prepareStatement("select firstName||' '||LastName as Name,nvl( (Select sum(ammount) from accbalence where accno=accounts.accno),0) as Balence,nvl(pic,'H:\\a pic\\no-profile.png') as picture from accounts where accno=?");
			ps.setInt(1,Integer.parseInt(this.t1.getText()));
			ResultSet rs = ps.executeQuery();
			 while(rs.next())
			 {
				cnt++; 
                                //set data in respective componet 
				 l3.setText(rs.getString("Name"));
				 l5.setText(rs.getString("Balence"));
                                 
                                javax.swing.ImageIcon im= new javax.swing.ImageIcon(rs.getString("picture"));
                                piclabel.setIcon(im);
                                 
                                 
                                 
			//make all component visible	 
			  l2.setVisible(true);l4.setVisible(true);
			l3.setVisible(true);l5.setVisible(true);sub1.setVisible(true);
			 }
			 con.close(); //close conneciton with database
                         if(cnt == 0)
                         { t1.setBorder(borderRed);
				JOptionPane.showMessageDialog((Component)null,"Invalid Accoun No. Click OK and try again","Warning",JOptionPane.WARNING_MESSAGE);
                         }
			
		   } catch(Exception ex){System.out.println(ex.getMessage()+"Exception");}
			}
}
   /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CheckBalence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CheckBalence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CheckBalence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CheckBalence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CheckBalence().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel piclabel;
    private javax.swing.JButton sub;
    private javax.swing.JButton sub1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
