
package banking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author GOLU
 */
public class EditResistration extends javax.swing.JFrame {
int ct=0;
    /**
     * Creates new form EditResistration
     */
    public EditResistration() {
       
        initComponents();
       setBounds(170,100,1115,490); //set window size of Edit Resistration from
       //first make all component invisible
        fNameLable.setVisible(false);fnameTxt.setVisible(false);surnameLable.setVisible(false);surnameTxt.setVisible(false);
        usernameLable2.setVisible(false);UserNameTxt2.setVisible(false);passLable1.setVisible(false);passTxt2.setVisible(false);
        passLable3.setVisible(false);passTxt3.setVisible(false); resister.setVisible(false);Cancel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
//INITIALIZE ALL VISIBLE COMPONENT
        userLable = new javax.swing.JLabel();
        usenameTxt = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        fNameLable = new javax.swing.JLabel();
        fnameTxt = new javax.swing.JTextField();
        surnameLable = new javax.swing.JLabel();
        surnameTxt = new javax.swing.JTextField();
        usernameLable2 = new javax.swing.JLabel();
        UserNameTxt2 = new javax.swing.JTextField();
        passLable1 = new javax.swing.JLabel();
        passLable3 = new javax.swing.JLabel();
        resister = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        oldPassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        passTxt2 = new javax.swing.JPasswordField();
        passTxt3 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        userLable.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        userLable.setForeground(new java.awt.Color(102, 102, 255));
        userLable.setText("USERNAME");
        getContentPane().add(userLable);
        userLable.setBounds(30, 190, 114, 25);

        usenameTxt.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(usenameTxt);
        usenameTxt.setBounds(190, 180, 176, 31);

        search.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        search.setForeground(new java.awt.Color(0, 51, 51));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(130, 290, 113, 32);

        fNameLable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fNameLable.setForeground(new java.awt.Color(102, 0, 0));
        fNameLable.setText("First Name");
        getContentPane().add(fNameLable);
        fNameLable.setBounds(500, 140, 97, 22);

        fnameTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(fnameTxt);
        fnameTxt.setBounds(680, 130, 171, 30);

        surnameLable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        surnameLable.setForeground(new java.awt.Color(102, 0, 0));
        surnameLable.setText("Surname");
        getContentPane().add(surnameLable);
        surnameLable.setBounds(890, 140, 82, 22);

        surnameTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(surnameTxt);
        surnameTxt.setBounds(1000, 130, 144, 30);

        usernameLable2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usernameLable2.setForeground(new java.awt.Color(102, 0, 0));
        usernameLable2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLable2.setText("Username");
        getContentPane().add(usernameLable2);
        usernameLable2.setBounds(500, 180, 92, 22);

        UserNameTxt2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(UserNameTxt2);
        UserNameTxt2.setBounds(680, 180, 171, 30);

        passLable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passLable1.setForeground(new java.awt.Color(102, 0, 0));
        passLable1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passLable1.setText("New Password");
        getContentPane().add(passLable1);
        passLable1.setBounds(470, 230, 133, 22);

        passLable3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passLable3.setForeground(new java.awt.Color(102, 0, 0));
        passLable3.setText("Confirm Password");
        getContentPane().add(passLable3);
        passLable3.setBounds(450, 280, 164, 22);

        resister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resister.setForeground(new java.awt.Color(0, 51, 51));
        resister.setText("Update");
        resister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resisterActionPerformed(evt);
            }
        });
        getContentPane().add(resister);
        resister.setBounds(600, 360, 97, 31);

        Cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cancel.setForeground(new java.awt.Color(0, 51, 51));
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel);
        Cancel.setBounds(760, 360, 93, 31);

        oldPassword.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        oldPassword.setForeground(new java.awt.Color(102, 102, 255));
        oldPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oldPassword.setText("Old Password");
        getContentPane().add(oldPassword);
        oldPassword.setBounds(30, 230, 137, 25);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(190, 230, 176, 33);

        passTxt2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(passTxt2);
        passTxt2.setBounds(680, 230, 171, 30);

        passTxt3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(passTxt3);
        passTxt3.setBounds(680, 280, 171, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EDIT RESISTRATION FORM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 20, 370, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("PIC DESTINATION PATH")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1190, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resisterActionPerformed
       try{
           update();
       }catch(Exception e){}
    }//GEN-LAST:event_resisterActionPerformed

    public void update() throws Exception{
        
        //check for all textbox is empty ??, if it is empty then repective box wil be red and there will be respective pop-up
    if(this.fnameTxt.getText().equals(""))
			{
                           //usenameTxt.setBorder(borderRed);
			   JOptionPane.showMessageDialog(null, "First IS EMPTY PLEASE ENTER YOUR USERNAME");
                        }
       else if(this.UserNameTxt2.getText().equals(""))
			{
                           //usenameTxt.setBorder(borderRed);
			   JOptionPane.showMessageDialog(null, "USERNAME IS EMPTY PLEASE ENTER YOUR USERNAME");
                        }
   else if(this.surnameTxt.getText().equals(""))
			{
                           //usenameTxt.setBorder(borderRed);
			   JOptionPane.showMessageDialog(null, "SURNAME IS EMPTY PLEASE ENTER YOURS SURNAME");
                        }
   else if(this.passTxt2.getText().equals(""))
			{
                           //usenameTxt.setBorder(borderRed);
			   JOptionPane.showMessageDialog(null, "PASSWORD FIELD IS EMPTY PLEASE ENTER  PASSWORD");
                        }
    else{
        int x=0;
    char[] s1= this.passTxt2.getPassword();
    char[] s2= this.passTxt3.getPassword();
    String s3 = new String(s1);
    String s4 = new String(s2);
    
    if(s3.equals(s4)){
        try{
    Class.forName("oracle.jdbc.driver.OracleDriver");
                         
    Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","USERNAME","PASSWORD");
       PreparedStatement ps = con.prepareStatement("update administrators set fName=?,surName =?,UserName =?,password =? where UserName =? ");
     			ps.setString(5,usenameTxt.getText());
                        ps.setString(1,fnameTxt.getText());
                    ps.setString(2,surnameTxt.getText());
                    ps.setString(3,UserNameTxt2.getText());
                    ps.setString(4,passTxt2.getText());


                    ps.executeQuery();
                    con.close();

     					JOptionPane.showMessageDialog(null, "Record Update SuccessFully");

             }catch(Exception e){}
    }else
           {
                JOptionPane.showMessageDialog(resister, "Password Does Not Match");
            }}
    
    }
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_CancelActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try{search();}catch(Exception e){}
    }//GEN-LAST:event_searchActionPerformed
public void search() throws Exception{

//      char[] s1= this.passTxt2.getAccessibleContext();
//    char[] s2= this.passTxt3.getPassword();
//    String s3 = new String(s1);
//    String s4 = new String(s2);
    try{
        
       if(this.usenameTxt.getText().equals(""))
			{
                           //usenameTxt.setBorder(borderRed);
			   JOptionPane.showMessageDialog(null, "USERNAME IS EMPTY PLEASE ENTER A RESISTERED USERNAME");
                        }
      else if(this.jPasswordField1.getText().equals(""))
			{
                           //usenameTxt.setBorder(borderRed);
			   JOptionPane.showMessageDialog(null, " PASSWORD FIELLD IS EMPTY PLEASE ENTER A RESISTERED PASSWORD");
                        }
    Class.forName("oracle.jdbc.driver.OracleDriver");
                         
    Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","USERNAME","PASSWORD");
       PreparedStatement ps = con.prepareStatement("Select fName,surName,UserName,password from administrators where userName=? and password=? ");
       ps.setString(1,usenameTxt.getText());
       ps.setString(2, jPasswordField1.getText());

       ResultSet rs = ps.executeQuery();
       while(rs.next()){
                      ct++;
                      
                      //make all componet visible and set all respective text
       fNameLable.setVisible(true);fnameTxt.setVisible(true);surnameLable.setVisible(true);surnameTxt.setVisible(true);
        usernameLable2.setVisible(true);UserNameTxt2.setVisible(true);passLable1.setVisible(true);passTxt2.setVisible(true);
        passLable3.setVisible(true);passTxt3.setVisible(true); resister.setVisible(true);Cancel.setVisible(true); 
                      
       fnameTxt.setText(rs.getString("fname"));
       surnameTxt.setText(rs.getString("surname"));
       UserNameTxt2.setText(rs.getString("username"));
       passTxt2.setText(rs.getString("password"));
       
      
       
       
       
       
       }
       con.close();//close the connection
       if(ct == 0)
                         { 
                                //t1.setBorder(borderRed);
			    JOptionPane.showMessageDialog(null, "INVALID USERNAME AND PASSWORD PLEASE ENTER VALID USER NAME AND PASSWORD");
                         }
    
    }catch(Exception e){JOptionPane.showMessageDialog(null, e.getMessage());}


}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditResistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditResistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditResistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditResistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditResistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField UserNameTxt2;
    private javax.swing.JLabel fNameLable;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel oldPassword;
    private javax.swing.JLabel passLable1;
    private javax.swing.JLabel passLable3;
    private javax.swing.JPasswordField passTxt2;
    private javax.swing.JPasswordField passTxt3;
    private javax.swing.JButton resister;
    private javax.swing.JButton search;
    private javax.swing.JLabel surnameLable;
    private javax.swing.JTextField surnameTxt;
    private javax.swing.JTextField usenameTxt;
    private javax.swing.JLabel userLable;
    private javax.swing.JLabel usernameLable2;
    // End of variables declaration//GEN-END:variables
}
