
package banking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author GOLU
 */
public class Resister extends javax.swing.JFrame {

    /**
     * Creates new form Resister
     */
    public Resister() {
        initComponents();
        setBounds(150,100,895,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signLable = new javax.swing.JLabel();
        FnameLable = new javax.swing.JLabel();
        fnameTxt = new javax.swing.JTextField();
        surnameLable = new javax.swing.JLabel();
        surNameTxt = new javax.swing.JTextField();
        mailLable = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        psswrdfld = new javax.swing.JPasswordField();
        pswrdLable = new javax.swing.JLabel();
        pswrdLable2 = new javax.swing.JLabel();
        psswrdfld2 = new javax.swing.JPasswordField();
        resister = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Cancel1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Sign Up Page");
        setBackground(new java.awt.Color(35, 178, 184));
        getContentPane().setLayout(null);

        signLable.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        signLable.setForeground(new java.awt.Color(51, 51, 255));
        signLable.setText("Sign Up");
        getContentPane().add(signLable);
        signLable.setBounds(40, 70, 116, 37);

        FnameLable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FnameLable.setForeground(new java.awt.Color(255, 51, 153));
        FnameLable.setText("First Name");
        getContentPane().add(FnameLable);
        FnameLable.setBounds(80, 160, 97, 22);

        fnameTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(fnameTxt);
        fnameTxt.setBounds(300, 150, 180, 30);

        surnameLable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        surnameLable.setForeground(new java.awt.Color(255, 51, 153));
        surnameLable.setText("Surname");
        getContentPane().add(surnameLable);
        surnameLable.setBounds(530, 150, 82, 22);

        surNameTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(surNameTxt);
        surNameTxt.setBounds(640, 150, 148, 30);

        mailLable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mailLable.setForeground(new java.awt.Color(255, 51, 153));
        mailLable.setText("Username");
        getContentPane().add(mailLable);
        mailLable.setBounds(90, 210, 92, 22);

        userNameTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(userNameTxt);
        userNameTxt.setBounds(300, 210, 180, 30);

        psswrdfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psswrdfldActionPerformed(evt);
            }
        });
        getContentPane().add(psswrdfld);
        psswrdfld.setBounds(300, 270, 180, 30);

        pswrdLable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pswrdLable.setForeground(new java.awt.Color(255, 51, 153));
        pswrdLable.setText("New Password");
        getContentPane().add(pswrdLable);
        pswrdLable.setBounds(70, 270, 133, 22);

        pswrdLable2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pswrdLable2.setForeground(new java.awt.Color(255, 51, 153));
        pswrdLable2.setText("Confirm Password");
        getContentPane().add(pswrdLable2);
        pswrdLable2.setBounds(60, 320, 164, 22);
        getContentPane().add(psswrdfld2);
        psswrdfld2.setBounds(300, 320, 180, 30);

        resister.setBackground(new java.awt.Color(255, 204, 204));
        resister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resister.setForeground(new java.awt.Color(0, 153, 153));
        resister.setText("Register");
        resister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resisterActionPerformed(evt);
            }
        });
        getContentPane().add(resister);
        resister.setBounds(140, 390, 150, 40);

        Cancel.setBackground(new java.awt.Color(255, 204, 204));
        Cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cancel.setForeground(new java.awt.Color(0, 153, 153));
        Cancel.setText("Clear");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel);
        Cancel.setBounds(320, 390, 150, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CREATING NEW USER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 30, 400, 50);

        Cancel1.setBackground(new java.awt.Color(255, 204, 204));
        Cancel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cancel1.setForeground(new java.awt.Color(0, 153, 153));
        Cancel1.setText("Cancel");
        Cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel1ActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel1);
        Cancel1.setBounds(490, 390, 150, 40);

        jLabel1.setBackground(new java.awt.Color(82, 185, 186));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\GOLU\\Desktop\\New folder\\edit_pic\\administrator.jpg")); // NOI18N
        jLabel1.setAutoscrolls(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resisterActionPerformed
        try{resister();}catch(Exception e){}
    }//GEN-LAST:event_resisterActionPerformed

    private void psswrdfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psswrdfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psswrdfldActionPerformed

    private void fnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameTxtActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        fnameTxt.setText("");surNameTxt.setText("");userNameTxt.setText("");psswrdfld.setText("");psswrdfld2.setText("");
    }//GEN-LAST:event_CancelActionPerformed

    private void Cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_Cancel1ActionPerformed
public void resister() throws Exception{
     if(this.fnameTxt.getText().equals(""))
			{
                           //usenameTxt.setBorder(borderRed);
			   JOptionPane.showMessageDialog(null, "FIRSTNAME NAME FIELD IS EMPTY PLEASE INSERT YOU FIRST FIRSTNAME");
                        }
     else if(this.surNameTxt.getText().equals(""))
			{
                           //usenameTxt.setBorder(borderRed);
			   JOptionPane.showMessageDialog(null, " SURNAME NAME FIELD IS EMPTY PLEASE INSERT YOU FIRST SURNAME");
                        }
     else if(this.userNameTxt.getText().equals(""))
			{
                           //usenameTxt.setBorder(borderRed);
			   JOptionPane.showMessageDialog(null, " USERNAME FIELD IS EMPTY PLEASE ENTER A RESISTERED USERNAME");
                        }
     else if(this.psswrdfld.getText().equals(""))
			{
                           //usenameTxt.setBorder(borderRed);
			   JOptionPane.showMessageDialog(null, " PASSWORD FIELD IS EMPTY PLEASE ENTER PASSWORD");
                        }
    
     else{
    int x=0;
    char[] s1= this.psswrdfld.getPassword();
    char[] s2= this.psswrdfld2.getPassword();
    String s3 = new String(s1);
    String s4 = new String(s2);
    
    if(s3.equals(s4)){
          try{
              
                Class.forName("oracle.jdbc.driver.OracleDriver");                  
       Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","USERNAME","PASSWORD");
       PreparedStatement ps4 = con.prepareStatement("insert into administrators values(ad_id.NEXTVAL,?,?,?,?)");
       ps4.setString(1,fnameTxt.getText());
       ps4.setString(2,surNameTxt.getText());
       ps4.setString(3,userNameTxt.getText());
       ps4.setString(4, s3);
       ps4.executeQuery();
                    x++;
                    
                    if (x > 0) 
                    {
                        JOptionPane.showMessageDialog(resister, "NEW USER ADDED SUCCESFULLY");
                    }

   }catch(Exception e){}
     } else
           {
                JOptionPane.showMessageDialog(resister, "Password Does Not Match");
            }

}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Cancel1;
    private javax.swing.JLabel FnameLable;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mailLable;
    private javax.swing.JPasswordField psswrdfld;
    private javax.swing.JPasswordField psswrdfld2;
    private javax.swing.JLabel pswrdLable;
    private javax.swing.JLabel pswrdLable2;
    private javax.swing.JButton resister;
    private javax.swing.JLabel signLable;
    private javax.swing.JTextField surNameTxt;
    private javax.swing.JLabel surnameLable;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
