package banking;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import javax.swing.table.*;
public class Tableview extends javax.swing.JFrame {

    
    public Tableview() {
        initComponents();
        try{
            fillData();
        }catch(Exception e){}
        setBounds(170,50,785,660);
    }
private void fillData() throws Exception
{
	try{

    	String columns[]={"Branch Code","Branch Name","Branch Address","Branch Manager","Contact_no","IFSC_Code" };
		int size=getsize();
		Object[][] rows=new Object[size][6];
	    int i=0;
		
		 Class.forName("oracle.jdbc.driver.OracleDriver");//RESISTER WITH DATABASE DRIVER
		//MAKE CONECTION DATABASE DRIVER MANAGER USING USERNAME AND PASSWORD
		Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","USERNAME","PASSWORD");
		
		    PreparedStatement ps=con.prepareStatement("Select bcode,bname,bstreet||' '||bdist||' '||bstate as baddr,bmng,bcont,ifscode from branch");
			ResultSet rs=ps.executeQuery();	
			
			 while(rs.next())
          {
			   
			  rows[i][0]=rs.getString(1);
			  rows[i][1]=rs.getString(2);
			  rows[i][2]=rs.getString(3);
			  rows[i][3]=rs.getString(4);
			  rows[i][4]=rs.getString(5);
			  rows[i][5]=rs.getString(6);
              i++;
		  }
		  
		  TableModel tm=new DefaultTableModel(rows,columns);
		  this.jTable1.setModel(tm);
		  con.close();
    }catch(Exception ex){System.out.println(ex.getMessage());}
	
}
public int getsize()
{
	int Size=0;
	try{
	    Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","USERNAME","PASSWORD");
        PreparedStatement ps=con.prepareStatement("Select count(*) from branch");
		 ResultSet rs = ps.executeQuery();
			 while(rs.next())
          {
			   Size=rs.getInt(1);
		  }}catch(Exception ex){System.out.println(ex.getMessage());}
		  return Size;
	
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setTitle("All Branches");
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Branch Code", "Branch Name", "Branch Address", "Branch Manager", "Contact_no", "IFSC_Code"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        scrollPane1.add(jScrollPane1);

        getContentPane().add(scrollPane1);
        scrollPane1.setBounds(24, 43, 718, 396);

        jLabel1.setIcon(new javax.swing.ImageIcon("PIC DESTINATION PATH")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tableview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tableview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tableview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tableview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tableview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
