package banking;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import javax.swing.border.Border;
import javax.swing.table.*;
public class TransferSummary extends javax.swing.JFrame {
java.text.SimpleDateFormat ft = new java.text.SimpleDateFormat("dd-MMM-yyyy");
				String dt1;
                                String dt2;
    
    public TransferSummary() {
            

        initComponents();
        //jLabel1.setVisible(false);	
//        this.jScrollPane1.setVisible(false);
//        setBounds(170,100,1200,1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setTitle("Mini Statements");

        l1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(102, 0, 0));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("Enter Account No.");

        t1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        l3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(102, 0, 0));
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("To Date");

        l2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(102, 0, 0));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("From Date");

        jDateChooser1.setDateFormatString("dd/MM/yyyy");

        jDateChooser2.setDateFormatString("dd/MM/yyyy");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Time & Date", "Mode", "Remark", "Type", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        scrollPane1.add(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l3)
                            .addComponent(l2)
                            .addComponent(l1))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(635, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(517, Short.MAX_VALUE)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(295, 295, 295))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(71, Short.MAX_VALUE)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(71, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   try{ 
//       dt1=ft.format(this.jDateChooser1.getDate());
//       java.util.Date ct= new java.util.Date();
//        java.util.Date ct2= new java.util.Date(dt1);
//        if(ct.after(ct2))
//        {
       search();
        //}
//        else{
//           JOptionPane.showMessageDialog(null, "invalid date");
//        }
   }catch(Exception e){System.out.println(e.getMessage());}
    }//GEN-LAST:event_jButton1ActionPerformed
public void search() throws Exception{
    
   
//    int dateint=0;
//    dateint=datecheck();
//    if(dateint<0)
//        JOptionPane.showMessageDialog(null, "invalid date");
   // else

try{
   
		                 dt1=ft.format(this.jDateChooser1.getDate()); //from date to get all transaction detail till To date i.e dt2
                                 dt2 = ft.format(this.jDateChooser2.getDate()); //To date 
    String columns[]={"Date & Time","Mode","Remark","Type","Ammount" };
			int Size=getsize();
                        
		    Object[][] rows=new Object[Size][5];
	        int i=0;
			
            Class.forName("oracle.jdbc.driver.OracleDriver");
	Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","USERNAME","PASSWORD");
PreparedStatement ps8=con.prepareStatement("Select to_char(doT,'dd/mm/yyyy') as dot,pMode,refNo,type,ammount from transactions where ACCNO = ? and dot between ? and ? order by dot desc");
      ps8.setInt(1,Integer.parseInt(t1.getText()));
      ps8.setString(2,dt1);
      ps8.setString(3,dt2);
    ResultSet rs = ps8.executeQuery();
while(rs.next())
          {
                   rows[i][0]=rs.getString("dot");
                  rows[i][1]=rs.getString("pMode");
                  rows[i][2]=rs.getString("refNo");
                  rows[i][3]=rs.getString("type");
                  rows[i][4]=rs.getString("ammount");
			
	           i++;
	    }
		  TableModel tm=new DefaultTableModel(rows,columns);
		  this.jTable1.setModel(tm);
		 this.jScrollPane1.setVisible(true);
          con.close();
}catch(Exception ex){System.out.println("jbjbhj"+ex.getMessage());}


}
public int datecheck(){
int dateSize = 0;
	try{
    Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","USERNAME","PASSWORD");
 PreparedStatement ps=con.prepareStatement("select to_date(to_char(sysdate,'dd-mm-yyyy'),'dd-mm-yyyy')-to_date('?','dd-mm-yyyy') from dual");
 ps.setString(1,dt1);
        ResultSet rs = ps.executeQuery();
			 while(rs.next())
          {
			   dateSize=rs.getInt(1);
		  }}catch(Exception ex){System.out.println(ex.getMessage());}
        System.out.println(dateSize);
		  return dateSize;
}
public int getsize()
{
    java.text.SimpleDateFormat ft = new java.text.SimpleDateFormat("MM/dd/yyyy");
				String dt1=ft.format(this.jDateChooser1.getDate());
                                String dt2 = ft.format(this.jDateChooser2.getDate());
	           int Size=0;
	try{
	Class.forName("oracle.jdbc.driver.OracleDriver");
		Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","USERNAME","PASSWORD");
        PreparedStatement ps=con.prepareStatement("Select count(*) as cnt  from transactions where ACCNO = ?");
		  ps.setInt(1,Integer.parseInt(t1.getText()));
                  //ps.
			ResultSet rs = ps.executeQuery();
			 while(rs.next())
          {
			   Size=rs.getInt("cnt");
	      }
		 }catch(Exception ex){System.out.println(ex.getMessage());}
		  return Size;
	
}
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
