package banking;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.net.*;
import javax.swing.border.Border;
public class Withdraw extends javax.swing.JFrame {
     int cnt=0;
     double sumammount=0.0;
      Border borderRed,borderBlack;
    /**
     * Creates new form Withdraw
     */
    public Withdraw() {
        borderBlack=BorderFactory.createLineBorder(Color.gray);
	borderRed=BorderFactory.createLineBorder(Color.red);
        initComponents();
        setBounds(170,100,1115,540);
        
        l2.setVisible(false);l3.setVisible(false);l4.setVisible(false);l5.setVisible(false);l6.setVisible(false);l7.setVisible(false);
l10.setVisible(false);this.jComboBox1.setVisible(false);l11.setVisible(false);t2.setVisible(false);
l12.setVisible(false);t4.setVisible(false);l13.setVisible(false);t5.setVisible(false);Withdraw.setVisible(false);
 Withdraw1.setVisible(false);   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        l11 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        l12 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        l13 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        Withdraw = new javax.swing.JButton();
        Withdraw1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Withdraw Form");
        getContentPane().setLayout(null);

        l1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(102, 0, 0));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("Enter Account No.");
        getContentPane().add(l1);
        l1.setBounds(48, 109, 164, 32);

        l9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l9.setForeground(new java.awt.Color(102, 102, 255));
        l9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l9.setText("Withdraw Form");
        getContentPane().add(l9);
        l9.setBounds(297, 48, 186, 43);

        t1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(242, 111, 258, 32);

        Search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Search.setForeground(new java.awt.Color(0, 51, 51));
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(553, 110, 119, 31);

        l2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(102, 0, 0));
        l2.setText("Name");
        getContentPane().add(l2);
        l2.setBounds(140, 180, 52, 17);

        l3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(l3);
        l3.setBounds(240, 170, 196, 28);

        l4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l4.setForeground(new java.awt.Color(102, 0, 0));
        l4.setText("Phone No.");
        getContentPane().add(l4);
        l4.setBounds(493, 171, 76, 17);

        l5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(l5);
        l5.setBounds(596, 171, 181, 28);

        l6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l6.setForeground(new java.awt.Color(102, 0, 0));
        l6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l6.setText("City");
        getContentPane().add(l6);
        l6.setBounds(818, 170, 49, 28);

        l7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(l7);
        l7.setBounds(885, 168, 151, 30);

        l10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l10.setForeground(new java.awt.Color(102, 0, 0));
        l10.setText("Transfer Mode");
        getContentPane().add(l10);
        l10.setBounds(24, 222, 143, 32);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Cheque", "Draft", "NEFT", "RTGS", "Transfer" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(185, 228, 111, 23);

        l11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l11.setForeground(new java.awt.Color(102, 0, 0));
        l11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l11.setText("Refference");
        getContentPane().add(l11);
        l11.setBounds(377, 222, 118, 32);

        t2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(t2);
        t2.setBounds(529, 225, 181, 32);

        l12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l12.setForeground(new java.awt.Color(102, 0, 0));
        l12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l12.setText("Ammount");
        getContentPane().add(l12);
        l12.setBounds(24, 279, 98, 22);

        t4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(t4);
        t4.setBounds(185, 278, 132, 30);

        l13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l13.setForeground(new java.awt.Color(102, 0, 0));
        l13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l13.setText("Remarks");
        getContentPane().add(l13);
        l13.setBounds(405, 275, 81, 30);

        t5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5);
        t5.setBounds(529, 276, 181, 34);

        Withdraw.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Withdraw.setForeground(new java.awt.Color(0, 51, 51));
        Withdraw.setText("WITHDRAW");
        Withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawActionPerformed(evt);
            }
        });
        getContentPane().add(Withdraw);
        Withdraw.setBounds(210, 390, 213, 46);

        Withdraw1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Withdraw1.setForeground(new java.awt.Color(0, 51, 51));
        Withdraw1.setText("CANCEL");
        Withdraw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Withdraw1ActionPerformed(evt);
            }
        });
        getContentPane().add(Withdraw1);
        Withdraw1.setBounds(490, 390, 213, 46);

        jLabel1.setIcon(new javax.swing.ImageIcon("PIC DESTINATION PATH")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        try{search();}catch(Exception e){}
    }//GEN-LAST:event_SearchActionPerformed

    private void WithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawActionPerformed
    try{Withdraw();}catch(Exception e){}
    }//GEN-LAST:event_WithdrawActionPerformed

    private void Withdraw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Withdraw1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_Withdraw1ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed
public String GetPhoneNo(String AccountNo)
    {
        String phone="";
        
        try{
					Class.forName("oracle.jdbc.driver.OracleDriver");
					Connection con = DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","USERNAME","PASSWORD");
					PreparedStatement ps = con.prepareStatement("Select mobile from accounts where ACCNO =?");
					
					ps.setInt(1,Integer.parseInt(AccountNo));
					
					ResultSet rs = ps.executeQuery();
					
					while(rs.next()){
                                        phone=rs.getString("mobile");
                                        }
        
        }catch(Exception ex){}
                
                
       return phone;
    }
    
    
    
    
    public void search() throws Exception{
try{
	if(t1.getText().equals(""))
			{
                            t1.setBorder(borderRed);
				JOptionPane.showMessageDialog((Component)null,"Please Enter Account Number","Warning",JOptionPane.WARNING_MESSAGE);
		
			}
                        t1.setBorder(borderBlack);
                        Class.forName("oracle.jdbc.driver.OracleDriver");
			Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","USERNAME","PASSWORD");
		    PreparedStatement ps=con.prepareStatement("Select FIRSTNAME||' '||MIDNAME||' '||LASTNAME as Name,MOBILE,CITY from ACCOUNTS where ACCNO = ?");
			ps.setInt(1,Integer.parseInt(t1.getText()));	
			ResultSet rs = ps.executeQuery();
			 while(rs.next())
          {
		cnt++;	  
	      l3.setText(rs.getString("Name"));
          l5.setText(rs.getString("MOBILE"));
          l7.setText(rs.getString("CITY"));
          
          l2.setVisible(true);l3.setVisible(true);l4.setVisible(true);l5.setVisible(true);l6.setVisible(true);l7.setVisible(true);
l10.setVisible(true);this.jComboBox1.setVisible(true);l11.setVisible(true);t2.setVisible(true);
l12.setVisible(true);t4.setVisible(true);l13.setVisible(true);t5.setVisible(true);Withdraw.setVisible(true);
Withdraw1.setVisible(true);          }
                         con.close();
                         if(cnt == 0)
                         { t1.setBorder(borderRed);
				JOptionPane.showMessageDialog((Component)null,"Invalid Accoun No. Click OK and try Again","Warning",JOptionPane.WARNING_MESSAGE);
                         }
}catch(Exception ex){JOptionPane.showMessageDialog(null, ex.getMessage());}

}

public void Withdraw() throws Exception{

    if(this.jComboBox1.getSelectedItem().equals("--Select--")){
					JOptionPane.showMessageDialog((Component)null,"Please Select Transfer Mode","Warning",JOptionPane.WARNING_MESSAGE);
					
			}
    else if(this.t4.getText().equals(""))
			{
				JOptionPane.showMessageDialog((Component)null,"Please Enter Amount","Warning",JOptionPane.WARNING_MESSAGE);
				
			}
    else if(this.t5.getText().equals(""))
			{
				JOptionPane.showMessageDialog((Component)null,"Please Remark","Warning",JOptionPane.WARNING_MESSAGE);
				
			}
			
			else 
			{    
		        sumammount = checkAmmount();
		        if(Double.parseDouble(t4.getText())<=sumammount)
				{
    try{  
		Class.forName("oracle.jdbc.driver.OracleDriver");
	    Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","USERNAME","PASSWORD");
	
    PreparedStatement ps=con.prepareStatement("insert into TRANSACTIONS values(traid.NEXTVAL,?,?,?,?,SYSDATE,?,?)");
	
	ps.setInt(1,Integer.parseInt(t1.getText()));
	ps.setString(2,"withdraw");
	ps.setString(3,this.jComboBox1.getSelectedItem().toString());
	ps.setString(4,t2.getText());
	ps.setInt(5,Integer.parseInt(t4.getText()));
	ps.setString(6,t5.getText());
	ps.executeQuery();
	con.close();
        JOptionPane.showMessageDialog(null, "Amount Withdraw SuccessFully");
        
        NewClass ob=new NewClass();
        ob.sendSms(GetPhoneNo(t1.getText()),"Thank you  for using SBI "+t4.getText()+" in Withdraw in your Account. current Balence is "+getbalence(t1.getText())+" ");
	t1.setText("");
    t5.setText(""); 
    t2.setText("");
    t4.setText("");	 
	
}catch(Exception ex){JOptionPane.showMessageDialog(null, ex.getMessage());}

                                }
                        else{
					JOptionPane.showMessageDialog(null, "Insuffecient ammount Cann't Withdraw Money");
				}
}
}
    
public double checkAmmount()
	{
	 double amt=0.0;
		try{
					 Class.forName("oracle.jdbc.driver.OracleDriver");
			         Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","USERNAME","PASSWORD");
					 PreparedStatement ps2=con.prepareStatement("select sum(ammount) as balence from accbalence where Accno=?");
		            ps2.setInt(1,Integer.parseInt(t1.getText()));
				ResultSet rs =	ps2.executeQuery();
					while(rs.next())
					{
					
					amt=rs.getDouble(1);
					}
				    con.close();
		}catch(Exception ex){ System.out.println(ex.getMessage());}
		return amt;
	}
    /**
     * @param args the command line arguments
     */

public String getbalence(String Accno) throws Exception{
    String bl="";
if(t1.getText().equals(""))
			{ 
				t1.setBorder(borderRed);
                                JOptionPane.showMessageDialog(null, "Please Enter Account Number");
			}
		else
		    {
				t1.setBorder(borderBlack);
		try{
			Class.forName("oracle.jdbc.driver.OracleDriver");
			Connection con=DriverManager.getConnection("jdbc:oracle:thin:@Localhost:1521:XE","USERNAME","PASSWORD");
			PreparedStatement ps=con.prepareStatement("select firstName||' '||LastName as Name,nvl( (Select sum(ammount) from accbalence where accno=accounts.accno),0) as Balence,nvl(pic,'H:\\EDUCATION\\IMPORTANT DOCUMENT\\10.jpg') as pic from accounts where accno=?");
			ps.setInt(1,Integer.parseInt(Accno));
			ResultSet rs = ps.executeQuery();
			 while(rs.next())
			 {
				cnt++; 
				// l3.setText(rs.getString("Name"));
				bl=rs.getString("Balence");
                                 
                               
                                 
                                 
				 
			
			 }
			 con.close();
                         if(cnt == 0)
                         { t1.setBorder(borderRed);
			    JOptionPane.showMessageDialog(null, "invalid Accoun No. Click OK and try again");
                         }
			
		   } catch(Exception ex){System.out.println(ex.getMessage()+"Exception");}
			}
return bl;
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Withdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JButton Withdraw;
    private javax.swing.JButton Withdraw1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
